spring:
  main:
    lazy-initialization: true
  application:
    name: es-data
  profiles:
    active: default
  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    username: elastic
    uris: http://127.0.0.1:9200

logging:
  level:
    root: info
    org.springframework.web: info
    org.hibernate: error
    vip.corejava.app.client: debug
  file:
    name: ./target/log/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 20
      max-history: 14